name: Smoke
run-name: Smoke test with hello on ${{ inputs.distro-name }}

on:
  workflow_call:
    inputs:
      distro-name:
        required: true
        type: string
      architecture:
        required: true
        type: string
      wsl-rootfs-url:
        required: true
        type: string
      wsl-rootfs-file:
        required: true
        type: string
      wsl-distro-name:
        required: true
        type: string
      wsl-enable-systemd:
        required: false
        type: boolean
        default: false
      wsl-enable-cloud-init-hack:
        required: false
        type: boolean
        default: false
      wsl-msi-url:
        required: false
        type: string
        default: https://github.com/microsoft/WSL/releases/download/2.2.4/wsl.2.2.4.0.x64.msi
      wsl-msi-file:
        required: false
        type: string
        default: wsl.2.2.4.0.x64.msi

env:
  WSL_UTF8: "1"

jobs:
  hello:
    name: "Smoke test with \"hello\" snap"
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install WSL
        uses: ./.github/actions/install-wsl

      - name: Import ${{ inputs.wsl-distro-name }} into WSL and run cloud-init
        id: setup-distro
        uses: ./.github/actions/setup-distro
        with:
          wsl-distro-name: ${{ inputs.wsl-distro-name }}
          wsl-rootfs-url: ${{ inputs.wsl-rootfs-url }}
          wsl-rootfs-file: ${{ inputs.wsl-rootfs-file }}
          wsl-enable-systemd: ${{ inputs.wsl-enable-systemd }}
          wsl-enable-cloud-init-hack: ${{ inputs.wsl-enable-cloud-init-hack }}

      - name: Install snapd snap
        uses: ./.github/actions/install-snap
        with:
          wsl-distro-name: ${{ inputs.wsl-distro-name }}
          snap-name: snapd

      - name: Install core22 snap
        uses: ./.github/actions/install-snap
        with:
          wsl-distro-name: ${{ inputs.wsl-distro-name }}
          snap-name: core22

      - name: Install hello snap
        uses: ./.github/actions/install-snap
        with:
          wsl-distro-name: ${{ inputs.wsl-distro-name }}
          snap-name: hello

      - name: Run hello snap application
        run: |
          Set-StrictMode -version latest
          $DistroName = '${{ inputs.wsl-distro-name }}'
          $SnapName = 'hello'

          Write-Output "Running ${SnapName} application."
          if ((wsl --distribution $DistroName snap run ${SnapName}) -notmatch 'Hello, world!') {
            Write-Error "Cannot run snap ${SnapName} application."
            exit 1
          }

      - name: Terminate ${{ inputs.distro-name }} ${{ inputs.architecture }} WSL instance
        if: always()
        run: |
          Set-StrictMode -version latest
          Write-Output "Terminating ${{ inputs.distro-name }} ${{ inputs.architecture }} WSL instance..."
          $DistroName = '${{ inputs.wsl-distro-name }}'

          Start-Process -NoNewWindow -Wait -FilePath "wsl.exe" -ArgumentList "--terminate $DistroName"
          Start-Process -NoNewWindow -Wait -FilePath "wsl.exe" -ArgumentList "--unregister $DistroName"
