name: Smoke
run-name: Smoke test with hello on ${{ inputs.distro-name }}

on:
  workflow_call:
    inputs:
      distro-name:
        required: true
        type: string
      architecture:
        required: true
        type: string
      wsl-rootfs-url:
        required: true
        type: string
      wsl-rootfs-file:
        required: true
        type: string
      wsl-distro-name:
        required: true
        type: string
      wsl-enable-systemd:
        required: false
        type: boolean
        default: false
      wsl-enable-cloud-init-hack:
        required: false
        type: boolean
        default: false
      wsl-msi-url:
        required: false
        type: string
        default: https://github.com/microsoft/WSL/releases/download/2.2.4/wsl.2.2.4.0.x64.msi
      wsl-msi-file:
        required: false
        type: string
        default: wsl.2.2.4.0.x64.msi

env:
  WSL_UTF8: "1"

jobs:
  hello:
    name: "Smoke test with \"hello\" snap"
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install WSL
        uses: ./.github/actions/install-wsl

      - name: Import ${{ inputs.wsl-distro-name }} into WSL and run cloud-init
        uses: ./.github/actions/setup-distro
        with:
          wsl-distro-name: ${{ inputs.wsl-distro-name }}
          wsl-rootfs-url: ${{ inputs.wsl-rootfs-url }}
          wsl-rootfs-file: ${{ inputs.wsl-rootfs-file }}
          wsl-enable-systemd: ${{ inputs.wsl-enable-systemd }}
          wsl-enable-cloud-init-hack: ${{ inputs.wsl-enable-cloud-init-hack }}

      - name: Download snapd snap
        uses: ./.github/actions/download-snap
        with:
          snap-name: snapd
          wsl-distro-name: ${{ inputs.wsl-distro-name }}

      - name: Download bare snap
        uses: ./.github/actions/download-snap
        with:
          snap-name: bare
          wsl-distro-name: ${{ inputs.wsl-distro-name }}

      - name: Download core22 snap
        uses: ./.github/actions/download-snap
        with:
          snap-name: core22
          wsl-distro-name: ${{ inputs.wsl-distro-name }}

      - name: Download hello snap
        uses: ./.github/actions/download-snap
        with:
          snap-name: hello
          wsl-distro-name: ${{ inputs.wsl-distro-name }}

      - name: Download snapcraft snap
        uses: ./.github/actions/download-snap
        with:
          snap-name: snapcraft
          wsl-distro-name: ${{ inputs.wsl-distro-name }}

      - name: Download lxd snap
        uses: ./.github/actions/download-snap
        with:
          snap-name: lxd
          wsl-distro-name: ${{ inputs.wsl-distro-name }}

      - name: Install snapd snap
        run: |
          Set-StrictMode -version latest
          $DistroName = '${{ inputs.wsl-distro-name }}'
          $SnapName = 'snapd'

          Write-Output "Starting snapd service."
          Start-Process -NoNewWindow -Wait -FilePath "wsl.exe" -ArgumentList "--distribution $DistroName systemctl start snapd"
          if ( ! $? ) {
            Write-Error "Cannot start snapd service."
            exit 1
          }

          Write-Output "Querying status of snapd service and socket."
          Start-Process -NoNewWindow -Wait -FilePath "wsl.exe" -ArgumentList "--distribution $DistroName systemctl status snapd.service snapd.socket"
          if ( ! $? ) {
            Write-Error "Cannot query status of snapd service and socket."
            exit 1
          }

          Write-Output "Version of snapd in the rootfs."
          Start-Process -NoNewWindow -Wait -FilePath "wsl.exe" -ArgumentList "--distribution $DistroName snap version"
          if ( ! $? ) {
            Write-Error "Cannot query snapd version."
            exit 1
          }

          Write-Output "Acknowledging assertion of ${SnapName}."
          Start-Process -NoNewWindow -Wait -FilePath "wsl.exe" -ArgumentList "--distribution $DistroName snap ack /srv/github-workspace/snaps/${SnapName}_*.assert"
          if ( ! $? ) {
            Write-Error "Cannot ack assertion of ${SnapName}."
            exit 1
          }

          Write-Output "Installing snapd as a snap."
          Start-Process -NoNewWindow -Wait -FilePath "wsl.exe" -ArgumentList "--distribution $DistroName snap install /srv/github-workspace/snaps/${SnapName}_*.snap"
          if ( ! $? ) {
            Write-Error "Cannot install snap ${SnapName}."
            exit 1
          }

          Write-Output "Version of snapd from the snapd snap."
          Start-Process -NoNewWindow -Wait -FilePath "wsl.exe" -ArgumentList "--distribution $DistroName snap version"
          if ( ! $? ) {
            Write-Error "Cannot query snapd version."
            exit 1
          }

          Write-Output "Querying status of snapd service and socket after snapd snap is installed."
          Start-Process -NoNewWindow -Wait -FilePath "wsl.exe" -ArgumentList "--distribution $DistroName systemctl status snapd.service snapd.socket"
          if ( ! $? ) {
            Write-Error "Cannot query status of snapd service and socket."
            exit 1
          }

      - name: Install core22 base snap
        run: |
          Set-StrictMode -version latest
          $DistroName = '${{ inputs.wsl-distro-name }}'
          $SnapName = 'core22'

          Write-Output "Acknowledging assertion of ${SnapName}."
          Start-Process -NoNewWindow -Wait -FilePath "wsl.exe" -ArgumentList "--distribution $DistroName snap ack /srv/github-workspace/snaps/${SnapName}_*.assert"
          if ( ! $? ) {
            Write-Error "Cannot ack assertion of ${SnapName}."
            exit 1
          }

          Write-Output "Installing ${SnapName} snap."
          Start-Process -NoNewWindow -Wait -FilePath "wsl.exe" -ArgumentList "--distribution $DistroName snap install /srv/github-workspace/snaps/${SnapName}_*.snap"
          if ( ! $? ) {
            Write-Error "Cannot install snap ${SnapName}."
            exit 1
          }

      - name: Install hello snap
        run: |
          Set-StrictMode -version latest
          $DistroName = '${{ inputs.wsl-distro-name }}'
          $SnapName = 'hello'

          Write-Output "Acknowledging assertion of ${SnapName}."
          Start-Process -NoNewWindow -Wait -FilePath "wsl.exe" -ArgumentList "--distribution $DistroName snap ack /srv/github-workspace/snaps/${SnapName}_*.assert"
          if ( ! $? ) {
            Write-Error "Cannot ack assertion of ${SnapName}."
            exit 1
          }

          Write-Output "Installing ${SnapName} snap."
          Start-Process -NoNewWindow -Wait -FilePath "wsl.exe" -ArgumentList "--distribution $DistroName snap install /srv/github-workspace/snaps/${SnapName}_*.snap"
          if ( ! $? ) {
            Write-Error "Cannot install snap ${SnapName}."
            exit 1
          }

      - name: Run hello snap application
        run: |
          Set-StrictMode -version latest
          $DistroName = '${{ inputs.wsl-distro-name }}'
          $SnapName = 'hello'

          Write-Output "Running ${SnapName} application."
          if ((wsl --distribution $DistroName snap run ${SnapName}) -notmatch 'Hello, world!') {
            Write-Error "Cannot run snap ${SnapName} application."
            exit 1
          }

      - name: Terminate ${{ inputs.distro-name }} ${{ inputs.architecture }} WSL instance
        if: always()
        run: |
          Set-StrictMode -version latest
          Write-Output "Terminating ${{ inputs.distro-name }} ${{ inputs.architecture }} WSL instance..."
          $DistroName = '${{ inputs.wsl-distro-name }}'

          Start-Process -NoNewWindow -Wait -FilePath "wsl.exe" -ArgumentList "--terminate $DistroName"
          Start-Process -NoNewWindow -Wait -FilePath "wsl.exe" -ArgumentList "--unregister $DistroName"
