name: Smoke

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch:

jobs:
  ubuntu:
    strategy:
      matrix:
        include:
          - codename: jammy
            version-id: "22.04"
            lts: true
            wsl-enable-systemd: true
            wsl-enable-cloud-init-hack: true
          - codename: noble
            version-id: "24.04"
            lts: true
    uses: ./.github/workflows/generic.yaml
    with:
      distro-name: Ubuntu ${{ matrix.version-id }}${{ matrix.lts == true && 'LTS' || '' }}
      architecture: amd64
      wsl-rootfs-url: https://cloud-images.ubuntu.com/wsl/${{ matrix.codename }}/current/ubuntu-${{ matrix.codename }}-wsl-amd64-wsl.rootfs.tar.gz
      wsl-rootfs-file: ubuntu-${{ matrix.codename }}-wsl-amd64-wsl.rootfs.tar.gz
      wsl-distro-name: Ubuntu-${{ matrix.version-id }}
