name: latest/stable

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch:

jobs:
  ubuntu:
    name: "Ubuntu ${{ matrix.version-id }}${{ matrix.lts == true && ' LTS' || '' }}"
    strategy:
      matrix:
        lts: [false]
        wsl-enable-systemd: [false]
        wsl-enable-cloud-init-hack: [false]
        include:
          - codename: jammy
            version-id: "22.04"
            wsl-enable-systemd: true
            wsl-enable-cloud-init-hack: true
          - codename: noble
            version-id: "24.04"
    uses: ./.github/workflows/generic.yaml
    with:
      distro-name: Ubuntu ${{ matrix.version-id }}
      architecture: amd64
      wsl-rootfs-url: https://cloud-images.ubuntu.com/wsl/${{ matrix.codename }}/current/ubuntu-${{ matrix.codename }}-wsl-amd64-wsl.rootfs.tar.gz
      wsl-rootfs-file: ubuntu-${{ matrix.codename }}-wsl-amd64-wsl.rootfs.tar.gz
      wsl-distro-name: Test-Ubuntu-${{ matrix.version-id }}
      wsl-enable-systemd: ${{ matrix.wsl-enable-systemd }}
      wsl-enable-cloud-init-hack: ${{ matrix.wsl-enable-cloud-init-hack }}
